/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AplikasiKasir;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class InputTransaksi extends javax.swing.JFrame {
    Connection connection = DatabaseConnection.getConnection();

    /**
     * Creates new form InputTransaksi
     */
    public InputTransaksi() {
        initComponents();
        txtIDTransaksi.setEnabled(false);
        txtTgl.setEnabled(false);
    }
    
    private void loadTableData() {
        DefaultTableModel dataTransaksi = (DefaultTableModel) tblTransaksi.getModel();
        dataTransaksi.setRowCount(0);

        String sql = "SELECT * FROM transaksi";
        try {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                String idTransaksi = rs.getString("id_transaksi");
                String namaPelanggan = rs.getString("nama_pelanggan");
                String menuPesanan = rs.getString("menu_pesanan");
                String menuPendamping = rs.getString("menu_pendamping");
                String minuman = rs.getString("minuman");
                String tanggal = rs.getString("tanggal");

                dataTransaksi.addRow(new Object[] {idTransaksi, namaPelanggan, menuPesanan, menuPendamping, minuman, tanggal});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error loading table data: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIDTransaksi = new javax.swing.JTextField();
        lblIDTransaksi = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();
        lblNamaPelanggan = new javax.swing.JLabel();
        lblMenuPesanan = new javax.swing.JLabel();
        txtMenuPesanan = new javax.swing.JComboBox<>();
        lblTgl = new javax.swing.JLabel();
        txtTgl = new javax.swing.JTextField();
        lblMenuPendamping = new javax.swing.JLabel();
        txtMenuPendamping = new javax.swing.JComboBox<>();
        txtMinuman = new javax.swing.JComboBox<>();
        lblMinuman = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnInput = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnStruk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        txtSukses = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 248, 243));

        jButton1.setBackground(new java.awt.Color(64, 93, 114));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaksi");

        txtIDTransaksi.setBackground(new java.awt.Color(247, 231, 220));
        txtIDTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtIDTransaksi.setForeground(new java.awt.Color(51, 51, 51));

        lblIDTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        lblIDTransaksi.setText("ID Transaksi");

        txtNamaPelanggan.setBackground(new java.awt.Color(247, 231, 220));
        txtNamaPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNamaPelanggan.setForeground(new java.awt.Color(51, 51, 51));

        lblNamaPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaPelanggan.setForeground(new java.awt.Color(51, 51, 51));
        lblNamaPelanggan.setText("Nama Pelanggan");

        lblMenuPesanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMenuPesanan.setForeground(new java.awt.Color(51, 51, 51));
        lblMenuPesanan.setText("Menu Pesanan");

        txtMenuPesanan.setBackground(new java.awt.Color(255, 255, 255));
        txtMenuPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMenuPesanan.setForeground(new java.awt.Color(51, 51, 51));
        txtMenuPesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Bebek Panggang Original", "Bebek Panggang Pedas Manis", "Bebek Panggang Sambal Matah", "Bebek Panggang Madu", "Bebek Panggang Lada Hitam" }));

        lblTgl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTgl.setForeground(new java.awt.Color(51, 51, 51));
        lblTgl.setText("Tanggal");

        txtTgl.setBackground(new java.awt.Color(247, 231, 220));
        txtTgl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTgl.setForeground(new java.awt.Color(51, 51, 51));

        lblMenuPendamping.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMenuPendamping.setForeground(new java.awt.Color(51, 51, 51));
        lblMenuPendamping.setText("Menu Pendamping");

        txtMenuPendamping.setBackground(new java.awt.Color(255, 255, 255));
        txtMenuPendamping.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMenuPendamping.setForeground(new java.awt.Color(51, 51, 51));
        txtMenuPendamping.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Nasi", "Ati Ampela", "Lalapan", "Tempe dan Tahu", "Gorengan", "Tidak Pake" }));

        txtMinuman.setBackground(new java.awt.Color(255, 255, 255));
        txtMinuman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMinuman.setForeground(new java.awt.Color(51, 51, 51));
        txtMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Jus Alpukat", "Jus Mangga", "Es teh", "Es jeruk", "Nutrisari", "Josua (extra jos susu)" }));

        lblMinuman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMinuman.setForeground(new java.awt.Color(51, 51, 51));
        lblMinuman.setText("Minuman");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnInput.setBackground(new java.awt.Color(204, 204, 204));
        btnInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInput.setForeground(new java.awt.Color(0, 0, 0));
        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnStruk.setBackground(new java.awt.Color(204, 204, 204));
        btnStruk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStruk.setForeground(new java.awt.Color(0, 0, 0));
        btnStruk.setText("Cetak Struk");
        btnStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStrukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnStruk))
                .addContainerGap())
        );

        tblTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Nama Pelanggan", "Menu Pesanan", "Side Menu", "Minuman", "Tanggal"
            }
        ));
        tblTransaksi.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tblTransaksiInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        txtSukses.setForeground(new java.awt.Color(0, 0, 0));
        txtSukses.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(322, 322, 322))
                            .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblMenuPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMenuPesanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblMenuPendamping, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMenuPendamping, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMinuman, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSukses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDTransaksi)
                    .addComponent(txtIDTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaPelanggan)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuPesanan)
                    .addComponent(txtMenuPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuPendamping)
                    .addComponent(txtMenuPendamping, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinuman)
                    .addComponent(txtMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTgl)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSukses)
                .addGap(227, 227, 227))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblTransaksi.getSelectedRow(); 
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus dari tabel!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String idTransaksi = tblTransaksi.getValueAt(selectedRow, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String query = "DELETE FROM transaksi WHERE id_transaksi = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, idTransaksi);
                int rowsDeleted = preparedStatement.executeUpdate();
                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                    loadTableData(); 
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStrukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStrukActionPerformed

    private void tblTransaksiInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblTransaksiInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTransaksiInputMethodTextChanged

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        String sqlData = "INSERT INTO transaksi (nama_pelanggan, menu_pesanan, menu_pendamping, minuman) VALUES (?, ?, ?, ?)";
        String idTransaksi = "";
        String namaPelanggan = txtNamaPelanggan.getText();
        String menuPes, menuPend, minuman;
        menuPes = (String)txtMenuPesanan.getSelectedItem();
        menuPend = (String)txtMenuPendamping.getSelectedItem();
        minuman = (String)txtMinuman.getSelectedItem();
        String tgl = "";  
        
        try{
            Transaksi transaksi = new Transaksi(idTransaksi, namaPelanggan, menuPes, menuPend, minuman, tgl);
            PreparedStatement pst = connection.prepareStatement(sqlData, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, namaPelanggan);
            pst.setString(2, menuPes);
            pst.setString(3, menuPend);
            pst.setString(4, minuman);            
            pst.executeUpdate();
            ResultSet generatedKeys = pst.getGeneratedKeys();
            if (generatedKeys.next()) {
                idTransaksi = generatedKeys.getString(1); 
            }

            String tampilData = "SELECT tanggal FROM transaksi WHERE id_transaksi = ?";
            PreparedStatement stmt = connection.prepareStatement(tampilData);
            stmt.setString(1, idTransaksi);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                tgl = rs.getString("tanggal"); 
            }
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            loadTableData();
            
            txtNamaPelanggan.setText("");
            txtMenuPesanan.setSelectedItem("Choose");
            txtMenuPendamping.setSelectedItem("Choose");
            txtMinuman.setSelectedItem("Choose");
        } catch(ValidasiInputExceptions e){
            txtSukses.setText("Error: " + e.getMessage());
            txtSukses.setForeground(Color.red);
        } catch(SQLException e){
            txtSukses.setText("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnInputActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnStruk;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDTransaksi;
    private javax.swing.JLabel lblMenuPendamping;
    private javax.swing.JLabel lblMenuPesanan;
    private javax.swing.JLabel lblMinuman;
    private javax.swing.JLabel lblNamaPelanggan;
    private javax.swing.JLabel lblTgl;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtIDTransaksi;
    private javax.swing.JComboBox<String> txtMenuPendamping;
    private javax.swing.JComboBox<String> txtMenuPesanan;
    private javax.swing.JComboBox<String> txtMinuman;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JLabel txtSukses;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables
}
