package AplikasiKasir;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import AplikasiKasir.DatabaseConnection;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Menu extends javax.swing.JFrame {
    private Connection connection;
     /**
     * Creates new form InputUser
     */
    public Menu() {
        initComponents();
        inisialisasiDatabase();
        txtIdMenu.setEnabled(false);
    }
    
    private void inisialisasiDatabase() {
        DatabaseConnection dbConnection = new DatabaseConnection();
        this.connection = dbConnection.getConnection();
        if (connection == null) {
            JOptionPane.showMessageDialog(this, 
                "Failed to connect", 
                "Database Connection Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void simpanTransaksi() {
        try {
            String idMenu = txtIdMenu.getText().trim();
            String namaMenu = txtNamaMenu.getText().trim();
            Double harga = Double.valueOf(txtHarga.getText().trim());
            String kategori = (String) txtKategori.getSelectedItem();
            String tanggal = java.time.LocalDate.now().toString();
            
         if (namaMenu.isEmpty() || kategori == null || kategori.isEmpty()) {
                lblStatus.setText("Semua field harus diisi!");
                lblStatus.setForeground(Color.red);
                return;
            }
         
         Transaksi transaksi = new Transaksi(
                idMenu, 
                "Anonymous", 
                namaMenu, 
                "N/A", 
                "N/A", 
                tanggal 
            );
         
          String query = "INSERT INTO transaksi (idTransaksi, namaPelanggan, menuPesanan, menuPendamping, minuman, tanggal) VALUES (?, ?, ?, ?, ?, ?)";

            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, transaksi.getIdTransaksi());
                preparedStatement.setString(2, transaksi.getNamaPelanggan());
                preparedStatement.setString(3, transaksi.getMenuPesanan());
                preparedStatement.setString(4, transaksi.getMenuPendamping());
                preparedStatement.setString(5, transaksi.getMinuman());
                preparedStatement.setString(6, transaksi.getTanggal());

                int rowsInserted = preparedStatement.executeUpdate();

                if (rowsInserted > 0) {
                    lblStatus.setText("Transaksi berhasil disimpan!");
                    lblStatus.setForeground(Color.green);
                    JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!", "Sukses!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    lblStatus.setText("Gagal menyimpan transaksi!");
                    lblStatus.setForeground(Color.red);
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi!", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                lblStatus.setText("Error: " + e.getMessage());
                lblStatus.setForeground(Color.red);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            lblStatus.setText("Error: " + e.getMessage());
            lblStatus.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void tampilkanStatus(String pesan, Color warna) {
        lblStatus.setText(pesan);
        lblStatus.setForeground(warna);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRole = new javax.swing.JComboBox<>();
        Menu = new javax.swing.JPanel();
        lblNamaMenu = new javax.swing.JLabel();
        btnInput = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        lblIdMenu = new javax.swing.JLabel();
        txtIdMenu = new javax.swing.JPasswordField();
        txtNamaMenu = new javax.swing.JPasswordField();
        txtHarga = new javax.swing.JPasswordField();
        txtKategori = new javax.swing.JComboBox<>();
        btnDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        txtRole.setBackground(new java.awt.Color(255, 255, 255));
        txtRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRole.setForeground(new java.awt.Color(0, 0, 0));
        txtRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "option", "kasir", "admin" }));
        txtRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(255, 248, 243));

        lblNamaMenu.setBackground(new java.awt.Color(102, 102, 102));
        lblNamaMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaMenu.setForeground(new java.awt.Color(102, 102, 102));
        lblNamaMenu.setText("Nama Menu");

        btnInput.setBackground(new java.awt.Color(64, 93, 114));
        btnInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInput.setForeground(new java.awt.Color(255, 255, 255));
        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        lblMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(102, 102, 102));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");

        lblHarga.setBackground(new java.awt.Color(102, 102, 102));
        lblHarga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(102, 102, 102));
        lblHarga.setText("Harga");

        lblStatus.setForeground(new java.awt.Color(51, 51, 51));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblKategori.setBackground(new java.awt.Color(102, 102, 102));
        lblKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKategori.setForeground(new java.awt.Color(102, 102, 102));
        lblKategori.setText("Kategori");

        lblIdMenu.setBackground(new java.awt.Color(102, 102, 102));
        lblIdMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIdMenu.setForeground(new java.awt.Color(102, 102, 102));
        lblIdMenu.setText("ID Menu");

        txtIdMenu.setBackground(new java.awt.Color(247, 231, 220));
        txtIdMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdMenu.setForeground(new java.awt.Color(51, 51, 51));
        txtIdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMenuActionPerformed(evt);
            }
        });

        txtNamaMenu.setBackground(new java.awt.Color(247, 231, 220));
        txtNamaMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNamaMenu.setForeground(new java.awt.Color(51, 51, 51));
        txtNamaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMenuActionPerformed(evt);
            }
        });

        txtHarga.setBackground(new java.awt.Color(247, 231, 220));
        txtHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(51, 51, 51));
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        txtKategori.setBackground(new java.awt.Color(255, 255, 255));
        txtKategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtKategori.setForeground(new java.awt.Color(0, 0, 0));
        txtKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Menu Utama", "Menu Pendamping", "Minuman" }));

        btnDetail.setBackground(new java.awt.Color(64, 93, 114));
        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnDetail.setText("Detail Menu");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdMenu)
                    .addComponent(lblNamaMenu)
                    .addComponent(lblHarga)
                    .addComponent(lblKategori))
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtKategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNamaMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                .addComponent(txtIdMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)))
                        .addGap(48, 48, 48))))
            .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetail)
                .addGap(16, 16, 16))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetail)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
    try {
        int idMenu = Integer.parseInt(txtIdMenu.getText().trim());
        String namaMenu = txtNamaMenu.getText().trim();
        Double harga = Double.valueOf(txtHarga.getText().trim());
        String kategori = (String) txtKategori.getSelectedItem();

        if (namaMenu.isEmpty() || kategori.isEmpty()){
            lblStatus.setText("Semua field harus diisi!");
            lblStatus.setForeground(Color.red);
            return;
        }

        String query = "INSERT INTO users (idMenu, namaMenu, harga, kategori) VALUES (?, ?, ?, ?, ?)";

        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, idMenu);
            preparedStatement.setString(2, namaMenu);
            preparedStatement.setDouble(3, harga);
            preparedStatement.setString(4, kategori);

            int rowsInserted = preparedStatement.executeUpdate();

            if (rowsInserted > 0) {
                lblStatus.setText("Registrasi berhasil!");
                lblStatus.setForeground(Color.green);
                JOptionPane.showMessageDialog(this, "Registrasi berhasil!", "Sukses!", JOptionPane.INFORMATION_MESSAGE);

                txtIdMenu.setText("");
                txtNamaMenu.setText("");
                txtHarga.setText("");
                txtKategori.setSelectedItem("Choose");
            } else {
                lblStatus.setText("Input menu gagal!");
                lblStatus.setForeground(Color.red);
                JOptionPane.showMessageDialog(this, "Gagal melakukan input menu!", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            lblStatus.setText("Error: " + e.getMessage());
            lblStatus.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        lblStatus.setText("ID User harus berupa angka!");
        lblStatus.setForeground(Color.red);
        JOptionPane.showMessageDialog(this, "ID Manu harus berupa angka!", "Input Error!", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        lblStatus.setText("Error: " + e.getMessage());
        lblStatus.setForeground(Color.red);
    }
    }//GEN-LAST:event_btnInputActionPerformed

    private void txtIdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMenuActionPerformed

    private void txtNamaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMenuActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrameAdmin back = new FrameAdmin();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        DetailMenu det = new DetailMenu();
        det.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDetailActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnInput;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIdMenu;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNamaMenu;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtHarga;
    private javax.swing.JPasswordField txtIdMenu;
    private javax.swing.JComboBox<String> txtKategori;
    private javax.swing.JPasswordField txtNamaMenu;
    private javax.swing.JComboBox<String> txtRole;
    // End of variables declaration//GEN-END:variables
}
