/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AplikasiKasir;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Asus
 */
public class Register extends javax.swing.JFrame {
    private Connection connection;
     /**
     * Creates new form InputUser
     */
    public Register() {
        initComponents();
        inisialisasiDatabase();
        txtIdUser.setEnabled(false);
        txtRole.setEnabled(false);
    }
    
    private void inisialisasiDatabase() {
        DatabaseConnection dbConnection = new DatabaseConnection();
        this.connection = dbConnection.getConnection();
        if (connection == null) {
            JOptionPane.showMessageDialog(this, 
                "Failed to connect", 
                "Database Connection Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblNamaKasir = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtIdUser = new javax.swing.JTextField();
        txtRole = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Register.setBackground(new java.awt.Color(255, 248, 243));

        lblUsername.setBackground(new java.awt.Color(102, 102, 102));
        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(102, 102, 102));
        lblUsername.setText("Username");

        btnRegister.setBackground(new java.awt.Color(64, 93, 114));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblRegister.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(102, 102, 102));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setText("Register");

        lblPassword.setBackground(new java.awt.Color(102, 102, 102));
        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(102, 102, 102));
        lblPassword.setText("Password");

        lblStatus.setForeground(new java.awt.Color(51, 51, 51));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(51, 51, 51));
        lblRole.setText("Role");

        lblNamaKasir.setBackground(new java.awt.Color(102, 102, 102));
        lblNamaKasir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKasir.setForeground(new java.awt.Color(102, 102, 102));
        lblNamaKasir.setText("Nama");

        lblIdUser.setBackground(new java.awt.Color(102, 102, 102));
        lblIdUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIdUser.setForeground(new java.awt.Color(102, 102, 102));
        lblIdUser.setText("ID User");

        txtPassword.setBackground(new java.awt.Color(247, 231, 220));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtUsername.setBackground(new java.awt.Color(247, 231, 220));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNama.setBackground(new java.awt.Color(247, 231, 220));
        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtIdUser.setBackground(new java.awt.Color(247, 231, 220));

        txtRole.setBackground(new java.awt.Color(247, 231, 220));
        txtRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRole.setForeground(new java.awt.Color(0, 0, 0));
        txtRole.setText("kasir");

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addContainerGap(39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLayout.createSequentialGroup()
                                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsername)
                                    .addComponent(lblIdUser))
                                .addGap(103, 103, 103))
                            .addGroup(RegisterLayout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGap(107, 107, 107)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLayout.createSequentialGroup()
                            .addComponent(lblNamaKasir)
                            .addGap(137, 137, 137)))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)))
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtIdUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtRole, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRole))))
                .addGap(12, 12, 12)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try {
            String namaKasir = txtNama.getText().trim();
            String username = txtUsername.getText().trim();
            String password = new String(txtPassword.getPassword()).trim();
            String role = txtRole.getText();

            if (namaKasir.isEmpty() || namaKasir.length() < 3) {
                lblStatus.setText("Nama Kasir harus diisi dan minimal 3 karakter!");
                lblStatus.setForeground(Color.red);
                return;
            }

            if (username.isEmpty() || username.length() < 4) {
                lblStatus.setText("Username harus diisi dan minimal 4 karakter!");
                lblStatus.setForeground(Color.red);
                return;
            }

            if (password.isEmpty() || password.length() < 6) {
                lblStatus.setText("Password harus diisi dan minimal 6 karakter!");
                lblStatus.setForeground(Color.red);
                return;
            }

            if (role == null || role.equals("Option")) {
                lblStatus.setText("Pilih role yang valid!");
                lblStatus.setForeground(Color.red);
                return;
            }

            String query = "INSERT INTO users (namaKasir, username, password, role) VALUES (?, ?, ?, ?)";

            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, namaKasir);
                preparedStatement.setString(2, username);
                preparedStatement.setString(3, password);
                preparedStatement.setString(4, role);

                int rowsInserted = preparedStatement.executeUpdate();

                if (rowsInserted > 0) {
                    lblStatus.setText("Registrasi berhasil!");
                    lblStatus.setForeground(Color.green);
                    JOptionPane.showMessageDialog(this, "Registrasi berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    InputUser login = new InputUser();
                    login.setVisible(true);
                    this.dispose();
                    
                    txtNama.setText("");
                    txtUsername.setText("");
                    txtPassword.setText("");
                } else {
                    lblStatus.setText("Registrasi gagal!");
                    lblStatus.setForeground(Color.red);
                    JOptionPane.showMessageDialog(this, "Gagal melakukan registrasi.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                if (e.getMessage().contains("Duplicate entry")) {
                    lblStatus.setText("Username sudah terdaftar!");
                } else {
                    lblStatus.setText("Database Error: " + e.getMessage());
                }
                lblStatus.setForeground(Color.red);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            lblStatus.setText("Error: " + e.getMessage());
            lblStatus.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Register;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblNamaKasir;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
