/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AplikasiKasir;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */

public class TampilanMenu extends JFrame {
    private JTable tableMenu;
    private JButton btnTampilkanData;

    public TampilanMenu() {
        // Set layout dan ukuran frame
        setTitle("Menu Restoran");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);

        // Tambahkan JTable
        tableMenu = new JTable();
        JScrollPane scrollPane = new JScrollPane(tableMenu);
        scrollPane.setBounds(20, 20, 540, 250);
        add(scrollPane);

        // Tambahkan JButton
        btnTampilkanData = new JButton("Tampilkan Data");
        btnTampilkanData.setBounds(220, 290, 150, 30);
        add(btnTampilkanData);

        // Event listener untuk tombol
        btnTampilkanData.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tampilkanData();
            }
        });

        // Tampilkan frame di tengah layar
        setLocationRelativeTo(null);
    }
    
     private void tampilkanData() {
        String url = "jdbc:mysql://localhost:3306/restoran_bebek"; // Ganti sesuai nama database Anda
        String user = "root"; // Ganti sesuai username MySQL Anda
        String password = ""; // Ganti sesuai password MySQL Anda

        try (Connection conn = DriverManager.getConnection(url, user, password)) {
            String query = "SELECT * FROM menu";
            PreparedStatement statement = conn.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();

            // Buat model untuk JTable
            DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nama Menu", "Harga", "Deskripsi"}, 0);
            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                String namaMenu = resultSet.getString("nama_menu");
                int harga = resultSet.getInt("harga");
                String deskripsi = resultSet.getString("deskripsi");
                model.addRow(new Object[]{id, namaMenu, harga, deskripsi});
            }
            tableMenu.setModel(model);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new TampilanMenu().setVisible(true));
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
